version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:845386813622:task-definition/hello-world-rest-api-code-pipeline:1"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api-pipeline"
          ContainerPort: "80"
        PlatformVersion: "LATEST"